/*
 * generated by Xtext 2.23.0
 */
package org.architecture.cnl.validation;

/**
 * This class contains custom validation rules.
 *
 * <p>See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ArchcnlValidator extends AbstractArchcnlValidator {

    //	public static final String INVALID_NAME = "invalidName";
    //
    //	@Check
    //	public void checkGreetingStartsWithCapital(Greeting greeting) {
    //		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
    //			warning("Name should start with a capital",
    //					ArchcnlPackage.Literals.GREETING__NAME,
    //					INVALID_NAME);
    //		}
    //	}

}
