/*
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ArchcnlValidator extends AbstractArchcnlValidator {
}
