/*
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.ide;


/**
 * Use this class to register ide components.
 */
public class ArchcnlIdeModule extends AbstractArchcnlIdeModule {
}
