/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Can Only Rule Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.architecture.cnl.archcnl.CanOnlyRuleType#getModifier <em>Modifier</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.CanOnlyRuleType#getObject <em>Object</em>}</li>
 * </ul>
 *
 * @see org.architecture.cnl.archcnl.ArchcnlPackage#getCanOnlyRuleType()
 * @model
 * @generated
 */
public interface CanOnlyRuleType extends EObject
{
  /**
   * Returns the value of the '<em><b>Modifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modifier</em>' attribute.
   * @see #setModifier(String)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getCanOnlyRuleType_Modifier()
   * @model
   * @generated
   */
  String getModifier();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.CanOnlyRuleType#getModifier <em>Modifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modifier</em>' attribute.
   * @see #getModifier()
   * @generated
   */
  void setModifier(String value);

  /**
   * Returns the value of the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' containment reference.
   * @see #setObject(org.architecture.cnl.archcnl.Object)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getCanOnlyRuleType_Object()
   * @model containment="true"
   * @generated
   */
  org.architecture.cnl.archcnl.Object getObject();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.CanOnlyRuleType#getObject <em>Object</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' containment reference.
   * @see #getObject()
   * @generated
   */
  void setObject(org.architecture.cnl.archcnl.Object value);

} // CanOnlyRuleType
