/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Datatype Property Assertion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.architecture.cnl.archcnl.DatatypePropertyAssertion#getString <em>String</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.DatatypePropertyAssertion#getInt <em>Int</em>}</li>
 * </ul>
 *
 * @see org.architecture.cnl.archcnl.ArchcnlPackage#getDatatypePropertyAssertion()
 * @model
 * @generated
 */
public interface DatatypePropertyAssertion extends RoleAssertion
{
  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getDatatypePropertyAssertion_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.DatatypePropertyAssertion#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getDatatypePropertyAssertion_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.DatatypePropertyAssertion#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

} // DatatypePropertyAssertion
