/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.architecture.cnl.archcnl.Model#getSentence <em>Sentence</em>}</li>
 * </ul>
 *
 * @see org.architecture.cnl.archcnl.ArchcnlPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Sentence</b></em>' containment reference list.
   * The list contents are of type {@link org.architecture.cnl.archcnl.Sentence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sentence</em>' containment reference list.
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getModel_Sentence()
   * @model containment="true"
   * @generated
   */
  EList<Sentence> getSentence();

} // Model
