/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negation Rule Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.architecture.cnl.archcnl.NegationRuleType#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.NegationRuleType#getObject <em>Object</em>}</li>
 * </ul>
 *
 * @see org.architecture.cnl.archcnl.ArchcnlPackage#getNegationRuleType()
 * @model
 * @generated
 */
public interface NegationRuleType extends EObject
{
  /**
   * Returns the value of the '<em><b>Subject</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subject</em>' containment reference.
   * @see #setSubject(ConceptExpression)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getNegationRuleType_Subject()
   * @model containment="true"
   * @generated
   */
  ConceptExpression getSubject();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.NegationRuleType#getSubject <em>Subject</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subject</em>' containment reference.
   * @see #getSubject()
   * @generated
   */
  void setSubject(ConceptExpression value);

  /**
   * Returns the value of the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' containment reference.
   * @see #setObject(org.architecture.cnl.archcnl.Object)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getNegationRuleType_Object()
   * @model containment="true"
   * @generated
   */
  org.architecture.cnl.archcnl.Object getObject();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.NegationRuleType#getObject <em>Object</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' containment reference.
   * @see #getObject()
   * @generated
   */
  void setObject(org.architecture.cnl.archcnl.Object value);

} // NegationRuleType
