/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.architecture.cnl.archcnl.ArchcnlPackage#getObjectRelation()
 * @model
 * @generated
 */
public interface ObjectRelation extends Relation
{
} // ObjectRelation
