/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Concept Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getRelation <em>Relation</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getCardinality <em>Cardinality</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getNumber <em>Number</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getConcept <em>Concept</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getData <em>Data</em>}</li>
 * </ul>
 *
 * @see org.architecture.cnl.archcnl.ArchcnlPackage#getObjectConceptExpression()
 * @model
 * @generated
 */
public interface ObjectConceptExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Relation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relation</em>' containment reference.
   * @see #setRelation(Relation)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getObjectConceptExpression_Relation()
   * @model containment="true"
   * @generated
   */
  Relation getRelation();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getRelation <em>Relation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relation</em>' containment reference.
   * @see #getRelation()
   * @generated
   */
  void setRelation(Relation value);

  /**
   * Returns the value of the '<em><b>Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardinality</em>' attribute.
   * @see #setCardinality(String)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getObjectConceptExpression_Cardinality()
   * @model
   * @generated
   */
  String getCardinality();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getCardinality <em>Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardinality</em>' attribute.
   * @see #getCardinality()
   * @generated
   */
  void setCardinality(String value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getObjectConceptExpression_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

  /**
   * Returns the value of the '<em><b>Concept</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concept</em>' containment reference.
   * @see #setConcept(ConceptExpression)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getObjectConceptExpression_Concept()
   * @model containment="true"
   * @generated
   */
  ConceptExpression getConcept();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getConcept <em>Concept</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Concept</em>' containment reference.
   * @see #getConcept()
   * @generated
   */
  void setConcept(ConceptExpression value);

  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference.
   * @see #setData(DataStatement)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getObjectConceptExpression_Data()
   * @model containment="true"
   * @generated
   */
  DataStatement getData();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.ObjectConceptExpression#getData <em>Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' containment reference.
   * @see #getData()
   * @generated
   */
  void setData(DataStatement value);

} // ObjectConceptExpression
