/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Property Assertion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.architecture.cnl.archcnl.ObjectPropertyAssertion#getConcept <em>Concept</em>}</li>
 * </ul>
 *
 * @see org.architecture.cnl.archcnl.ArchcnlPackage#getObjectPropertyAssertion()
 * @model
 * @generated
 */
public interface ObjectPropertyAssertion extends RoleAssertion
{
  /**
   * Returns the value of the '<em><b>Concept</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concept</em>' containment reference.
   * @see #setConcept(Concept)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getObjectPropertyAssertion_Concept()
   * @model containment="true"
   * @generated
   */
  Concept getConcept();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.ObjectPropertyAssertion#getConcept <em>Concept</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Concept</em>' containment reference.
   * @see #getConcept()
   * @generated
   */
  void setConcept(Concept value);

} // ObjectPropertyAssertion
