/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.architecture.cnl.archcnl.Relation#getRelationName <em>Relation Name</em>}</li>
 * </ul>
 *
 * @see org.architecture.cnl.archcnl.ArchcnlPackage#getRelation()
 * @model
 * @generated
 */
public interface Relation extends EObject
{
  /**
   * Returns the value of the '<em><b>Relation Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relation Name</em>' attribute.
   * @see #setRelationName(String)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getRelation_RelationName()
   * @model
   * @generated
   */
  String getRelationName();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.Relation#getRelationName <em>Relation Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relation Name</em>' attribute.
   * @see #getRelationName()
   * @generated
   */
  void setRelationName(String value);

} // Relation
