/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.architecture.cnl.archcnl.Sentence#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.Sentence#getRuletype <em>Ruletype</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.Sentence#getFacts <em>Facts</em>}</li>
 * </ul>
 *
 * @see org.architecture.cnl.archcnl.ArchcnlPackage#getSentence()
 * @model
 * @generated
 */
public interface Sentence extends EObject
{
  /**
   * Returns the value of the '<em><b>Subject</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subject</em>' containment reference.
   * @see #setSubject(ConceptExpression)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getSentence_Subject()
   * @model containment="true"
   * @generated
   */
  ConceptExpression getSubject();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.Sentence#getSubject <em>Subject</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subject</em>' containment reference.
   * @see #getSubject()
   * @generated
   */
  void setSubject(ConceptExpression value);

  /**
   * Returns the value of the '<em><b>Ruletype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ruletype</em>' containment reference.
   * @see #setRuletype(EObject)
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getSentence_Ruletype()
   * @model containment="true"
   * @generated
   */
  EObject getRuletype();

  /**
   * Sets the value of the '{@link org.architecture.cnl.archcnl.Sentence#getRuletype <em>Ruletype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ruletype</em>' containment reference.
   * @see #getRuletype()
   * @generated
   */
  void setRuletype(EObject value);

  /**
   * Returns the value of the '<em><b>Facts</b></em>' containment reference list.
   * The list contents are of type {@link org.architecture.cnl.archcnl.FactStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Facts</em>' containment reference list.
   * @see org.architecture.cnl.archcnl.ArchcnlPackage#getSentence_Facts()
   * @model containment="true"
   * @generated
   */
  EList<FactStatement> getFacts();

} // Sentence
