/*
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractArchcnlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.architecture.cnl.archcnl.ArchcnlPackage.eINSTANCE);
		return result;
	}
}
