PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX conformance: <http://www.semanticweb.org/sandr/ontologies/2018/4/architectureconformance#>
PREFIX famix: <http://arch-ont.org/ontologies/famix.owl#>
PREFIX architecture: <http://www.arch-ont.org/ontologies/architecture.owl#>

SELECT ?aggregate ?name
WHERE {
GRAPH ?g
  {
    ?aggregate rdf:type architecture:Aggregate.
    ?x conformance:validatesVersion "1.0"^^xsd:string.
    ?aggregate famix:hasName ?name.
  }}
