/**
 * generated by Xtext 2.22.0
 */
package org.architecture.cnl.archcnl.impl;

import org.architecture.cnl.archcnl.ArchcnlPackage;
import org.architecture.cnl.archcnl.ConceptExpression;
import org.architecture.cnl.archcnl.ConditionalRuleType;
import org.architecture.cnl.archcnl.Relation;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Conditional Rule Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.architecture.cnl.archcnl.impl.ConditionalRuleTypeImpl#getStart <em>Start</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.impl.ConditionalRuleTypeImpl#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.impl.ConditionalRuleTypeImpl#getRelation <em>Relation</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.impl.ConditionalRuleTypeImpl#getObject <em>Object</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.impl.ConditionalRuleTypeImpl#getRelation2 <em>Relation2</em>}</li>
 *   <li>{@link org.architecture.cnl.archcnl.impl.ConditionalRuleTypeImpl#getObject2 <em>Object2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConditionalRuleTypeImpl extends MinimalEObjectImpl.Container implements ConditionalRuleType
{
  /**
   * The default value of the '{@link #getStart() <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStart()
   * @generated
   * @ordered
   */
  protected static final String START_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStart() <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStart()
   * @generated
   * @ordered
   */
  protected String start = START_EDEFAULT;

  /**
   * The cached value of the '{@link #getSubject() <em>Subject</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubject()
   * @generated
   * @ordered
   */
  protected ConceptExpression subject;

  /**
   * The cached value of the '{@link #getRelation() <em>Relation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelation()
   * @generated
   * @ordered
   */
  protected Relation relation;

  /**
   * The cached value of the '{@link #getObject() <em>Object</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObject()
   * @generated
   * @ordered
   */
  protected ConceptExpression object;

  /**
   * The cached value of the '{@link #getRelation2() <em>Relation2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelation2()
   * @generated
   * @ordered
   */
  protected Relation relation2;

  /**
   * The cached value of the '{@link #getObject2() <em>Object2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObject2()
   * @generated
   * @ordered
   */
  protected ConceptExpression object2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConditionalRuleTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ArchcnlPackage.Literals.CONDITIONAL_RULE_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStart()
  {
    return start;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStart(String newStart)
  {
    String oldStart = start;
    start = newStart;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__START, oldStart, start));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConceptExpression getSubject()
  {
    return subject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSubject(ConceptExpression newSubject, NotificationChain msgs)
  {
    ConceptExpression oldSubject = subject;
    subject = newSubject;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__SUBJECT, oldSubject, newSubject);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubject(ConceptExpression newSubject)
  {
    if (newSubject != subject)
    {
      NotificationChain msgs = null;
      if (subject != null)
        msgs = ((InternalEObject)subject).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__SUBJECT, null, msgs);
      if (newSubject != null)
        msgs = ((InternalEObject)newSubject).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__SUBJECT, null, msgs);
      msgs = basicSetSubject(newSubject, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__SUBJECT, newSubject, newSubject));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Relation getRelation()
  {
    return relation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRelation(Relation newRelation, NotificationChain msgs)
  {
    Relation oldRelation = relation;
    relation = newRelation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION, oldRelation, newRelation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelation(Relation newRelation)
  {
    if (newRelation != relation)
    {
      NotificationChain msgs = null;
      if (relation != null)
        msgs = ((InternalEObject)relation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION, null, msgs);
      if (newRelation != null)
        msgs = ((InternalEObject)newRelation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION, null, msgs);
      msgs = basicSetRelation(newRelation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION, newRelation, newRelation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConceptExpression getObject()
  {
    return object;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetObject(ConceptExpression newObject, NotificationChain msgs)
  {
    ConceptExpression oldObject = object;
    object = newObject;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT, oldObject, newObject);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObject(ConceptExpression newObject)
  {
    if (newObject != object)
    {
      NotificationChain msgs = null;
      if (object != null)
        msgs = ((InternalEObject)object).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT, null, msgs);
      if (newObject != null)
        msgs = ((InternalEObject)newObject).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT, null, msgs);
      msgs = basicSetObject(newObject, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT, newObject, newObject));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Relation getRelation2()
  {
    return relation2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRelation2(Relation newRelation2, NotificationChain msgs)
  {
    Relation oldRelation2 = relation2;
    relation2 = newRelation2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION2, oldRelation2, newRelation2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelation2(Relation newRelation2)
  {
    if (newRelation2 != relation2)
    {
      NotificationChain msgs = null;
      if (relation2 != null)
        msgs = ((InternalEObject)relation2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION2, null, msgs);
      if (newRelation2 != null)
        msgs = ((InternalEObject)newRelation2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION2, null, msgs);
      msgs = basicSetRelation2(newRelation2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION2, newRelation2, newRelation2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConceptExpression getObject2()
  {
    return object2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetObject2(ConceptExpression newObject2, NotificationChain msgs)
  {
    ConceptExpression oldObject2 = object2;
    object2 = newObject2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT2, oldObject2, newObject2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObject2(ConceptExpression newObject2)
  {
    if (newObject2 != object2)
    {
      NotificationChain msgs = null;
      if (object2 != null)
        msgs = ((InternalEObject)object2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT2, null, msgs);
      if (newObject2 != null)
        msgs = ((InternalEObject)newObject2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT2, null, msgs);
      msgs = basicSetObject2(newObject2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT2, newObject2, newObject2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__SUBJECT:
        return basicSetSubject(null, msgs);
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION:
        return basicSetRelation(null, msgs);
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT:
        return basicSetObject(null, msgs);
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION2:
        return basicSetRelation2(null, msgs);
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT2:
        return basicSetObject2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__START:
        return getStart();
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__SUBJECT:
        return getSubject();
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION:
        return getRelation();
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT:
        return getObject();
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION2:
        return getRelation2();
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT2:
        return getObject2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__START:
        setStart((String)newValue);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__SUBJECT:
        setSubject((ConceptExpression)newValue);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION:
        setRelation((Relation)newValue);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT:
        setObject((ConceptExpression)newValue);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION2:
        setRelation2((Relation)newValue);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT2:
        setObject2((ConceptExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__START:
        setStart(START_EDEFAULT);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__SUBJECT:
        setSubject((ConceptExpression)null);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION:
        setRelation((Relation)null);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT:
        setObject((ConceptExpression)null);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION2:
        setRelation2((Relation)null);
        return;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT2:
        setObject2((ConceptExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__START:
        return START_EDEFAULT == null ? start != null : !START_EDEFAULT.equals(start);
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__SUBJECT:
        return subject != null;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION:
        return relation != null;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT:
        return object != null;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__RELATION2:
        return relation2 != null;
      case ArchcnlPackage.CONDITIONAL_RULE_TYPE__OBJECT2:
        return object2 != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (start: ");
    result.append(start);
    result.append(')');
    return result.toString();
  }

} //ConditionalRuleTypeImpl
