PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX conformance: <http://arch-ont.org/ontologies/architectureconformance#>
PREFIX famix: <http://arch-ont.org/ontologies/famix.owl#>
PREFIX architecture: <http://www.arch-ont.org/ontologies/architecture.owl#>

SELECT DISTINCT ?cnl ?subject ?object
WHERE {
GRAPH ?g
  {
    ?rule rdf:type conformance:ArchitectureRule.
    ?rule conformance:hasRuleRepresentation ?cnl.
    ?violation conformance:violates ?rule.
    ?proof conformance:proofs ?violation.
    ?proof conformance:hasAssertedStatement ?asserted. 
    ?asserted conformance:hasSubject ?x.
    ?asserted conformance:hasObject ?y.
    ?x famix:hasName ?subject.
    # Optional, because the "Every Aggregate must residein a DomainRing" rule's object has no "famix:hasName" attribute.
    OPTIONAL {?y famix:hasName ?object.}
  }
}
ORDER BY ?cnl
